/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numbringsystemsconverter;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdallah
 */
public class NumbersConverter extends javax.swing.JFrame {

    /**
     * Creates new form NumbersConverter
     */
    public NumbersConverter() {
        initComponents();
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T1 = new javax.swing.JTextField();
        L1 = new javax.swing.JLabel();
        DecButton = new javax.swing.JButton();
        BinaryButton = new javax.swing.JButton();
        OctButton = new javax.swing.JButton();
        HexButton = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        L10 = new javax.swing.JLabel();
        ConDecText = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        ConBinText = new javax.swing.JTextField();
        Label8 = new javax.swing.JLabel();
        ConOctText = new javax.swing.JTextField();
        ConHexText = new javax.swing.JTextField();
        Label16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NumberBaseConverter");
        setBackground(new java.awt.Color(255, 204, 204));
        setBounds(new java.awt.Rectangle(420, 200, 0, 0));
        setForeground(new java.awt.Color(255, 204, 204));

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });

        L1.setText("Enter Ur number");

        DecButton.setText("Decimal");
        DecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecButtonActionPerformed(evt);
            }
        });

        BinaryButton.setText("Binary");
        BinaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinaryButtonActionPerformed(evt);
            }
        });

        OctButton.setText("Oct");
        OctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctButtonActionPerformed(evt);
            }
        });

        HexButton.setText("Hex");
        HexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexButtonActionPerformed(evt);
            }
        });

        Panel1.setBackground(new java.awt.Color(255, 204, 153));
        Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N
        Panel1.setForeground(new java.awt.Color(204, 255, 204));

        L10.setText("Decimal form");

        Label2.setText("Binary form");

        Label8.setText("Oct form");

        Label16.setText("Hex form");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConDecText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L10)
                    .addComponent(Label8)
                    .addComponent(ConOctText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label2)
                    .addComponent(ConBinText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConHexText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label16))
                .addGap(31, 31, 31))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(L10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConDecText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(Label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConBinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addComponent(Label8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConOctText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addComponent(Label16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConHexText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(T1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(L1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BinaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(HexButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DecButton)
                    .addComponent(BinaryButton)
                    .addComponent(OctButton)
                    .addComponent(HexButton))
                .addGap(18, 18, 18)
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void DecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecButtonActionPerformed
    String d; int num;
    try
    {   
        d=T1.getText();
        if(d.equals(""))
        {num=0;}
        else
        { num=Integer.parseInt(d);}
        
        
        ConDecText.setText(Integer.toString(num));
        ConOctText.setText(Integer.toOctalString(num));
        ConBinText.setText(Integer.toBinaryString(num));
        ConHexText.setText(Integer.toHexString(num));
        
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, "invaild Decimal number","ERROR !!",JOptionPane.ERROR_MESSAGE);
        T1.setText("");
        ConDecText.setText("");
        ConOctText.setText("");
        ConBinText.setText("");
        ConHexText.setText("");
    }


    }//GEN-LAST:event_DecButtonActionPerformed

    private void BinaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinaryButtonActionPerformed
      String d,t; int num=0,index;
      d=T1.getText();
      index=d.length();
        try {
      
     for(int i=0; i<=index-1; i++)
     {
         t=d.substring(i,i+1);
         System.out.println(t);
         if("1".equals(t))
         {
             System.out.println("Great");
             num+=(1*(int)Math.pow(2,index-1-i));
         }
         else if("0".equals(t))
         {
             System.out.println("Great");
             num+=(0*(int)Math.pow(2,index-1-i));
         }
         else
         {  
            num=0;
            this.BinaryException();
            break;
         }   
     }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"invalid Binary Number","ERROR !!",JOptionPane.ERROR_MESSAGE);
            T1.setText("");
        }
        
        ConDecText.setText(Integer.toString(num));
        ConOctText.setText(Integer.toOctalString(num));
        ConBinText.setText(Integer.toBinaryString(num));
        ConHexText.setText(Integer.toHexString(num));
    
    }//GEN-LAST:event_BinaryButtonActionPerformed

    private void OctButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctButtonActionPerformed
  String d,t; int num=0,index;
      d=T1.getText();
      index=d.length();
        try {
      
     for(int i=0; i<=index-1; i++)
     {
         t=d.substring(i,i+1);
         System.out.println(t);
         if("1".equals(t))
         {
             System.out.println("Great");
             num+=(1*(int)Math.pow(8,index-1-i));
         }
         else if("0".equals(t))
         {
             System.out.println("Great");
             num+=(0*(int)Math.pow(8,index-1-i));
         }
              else if("2".equals(t))
         {
             System.out.println("Great");
             num+=(2*(int)Math.pow(8,index-1-i));
         }
              else if("3".equals(t))
         {
             System.out.println("Great");
             num+=(3*(int)Math.pow(8,index-1-i));
         }
              else if("4".equals(t))
         {
             System.out.println("Great");
             num+=(4*(int)Math.pow(8,index-1-i));
         }
              else if("5".equals(t))
         {
             System.out.println("Great");
             num+=(5*(int)Math.pow(8,index-1-i));
         }
              else if("6".equals(t))
         {
             System.out.println("Great");
             num+=(6*(int)Math.pow(8,index-1-i));
         }
              else if("7".equals(t))
         {
             System.out.println("Great");
             num+=(7*(int)Math.pow(8,index-1-i));
         }
         else
         {
            num=0;
            this.BinaryException();
            break;
         }   
     }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"invalid Octal Number","ERROR !!",JOptionPane.ERROR_MESSAGE);
            T1.setText("");
        }
        
        ConDecText.setText(Integer.toString(num));
        ConOctText.setText(Integer.toOctalString(num));
        ConBinText.setText(Integer.toBinaryString(num));
        ConHexText.setText(Integer.toHexString(num));
    
    }//GEN-LAST:event_OctButtonActionPerformed

    private void HexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexButtonActionPerformed
       
    String d,t; int num=0,index;
      d=T1.getText();
      index=d.length();
        try {
      
     for(int i=0; i<=index-1; i++)
     {
         t=d.substring(i,i+1);
         System.out.println(t);
         
         if("0".equals(t))
         {  num+=(0*(int)Math.pow(16,index-1-i));}
         
            else if("1".equals(t))
         {  num+=(1*(int)Math.pow(16,index-1-i));}
            
            else if("2".equals(t))
         {  num+=(2*(int)Math.pow(16,index-1-i));}
           
            else if("3".equals(t))
         {  num+=(3*(int)Math.pow(16,index-1-i));}
         
            else if("4".equals(t))
         {  num+=(4*(int)Math.pow(16,index-1-i));}
            
            else if("5".equals(t))
         {  num+=(5*(int)Math.pow(16,index-1-i));}
            
            else if("6".equals(t))
         {  num+=(6*(int)Math.pow(16,index-1-i));}
            
            else if("7".equals(t))
         {  num+=(7*(int)Math.pow(16,index-1-i));}
              
            else if("8".equals(t))
         {  num+=(8*(int)Math.pow(16,index-1-i));}
           
            else if("9".equals(t))
         {  num+=(9*(int)Math.pow(16,index-1-i));}
            
            else if("a".equalsIgnoreCase(t))
         {  num+=(10*(int)Math.pow(16,index-1-i));}
            
              else if("b".equalsIgnoreCase(t))
         {  num+=(11*(int)Math.pow(16,index-1-i));}
              
              else if("c".equalsIgnoreCase(t))
         {  num+=(12*(int)Math.pow(16,index-1-i));}
              
              else if("d".equalsIgnoreCase(t))
         {  num+=(13*(int)Math.pow(16,index-1-i)); }
            
              else if("e".equalsIgnoreCase(t))
         {  num+=(14*(int)Math.pow(16,index-1-i));}

              else if("f".equalsIgnoreCase(t))
         {  num+=(15*(int)Math.pow(16,index-1-i)); }
        
              else 
            {
            num=0;
            this.BinaryException();
            break;
            }   
     }
            
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"invalid Hex Number","ERROR !!",JOptionPane.ERROR_MESSAGE);
            T1.setText("");
        }
        
        ConDecText.setText(Integer.toString(num));
        ConOctText.setText(Integer.toOctalString(num));
        ConBinText.setText(Integer.toBinaryString(num));
        ConHexText.setText(Integer.toHexString(num));
    
    }//GEN-LAST:event_HexButtonActionPerformed

    /**
     *
     * @throws Exception
     */
    public void BinaryException() throws Exception
     {
         throw new Exception();
     }
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumbersConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumbersConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumbersConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumbersConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumbersConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BinaryButton;
    private javax.swing.JTextField ConBinText;
    private javax.swing.JTextField ConDecText;
    private javax.swing.JTextField ConHexText;
    private javax.swing.JTextField ConOctText;
    private javax.swing.JButton DecButton;
    private javax.swing.JButton HexButton;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label8;
    private javax.swing.JButton OctButton;
    private javax.swing.JPanel Panel1;
    private javax.swing.JTextField T1;
    // End of variables declaration//GEN-END:variables
}
